#!/usr/bin/env bun
/**
 * Generate the long, noisy, failing test suite used to compare a foreground
 * `bash` run against a `bgrun` job (see docs/dogfooding.md).
 *
 * WHY A GENERATOR AND NOT A CHECKED-IN SUITE
 * ------------------------------------------
 * `bun test` discovers every `*.test.ts` in the tree and does NOT respect
 * .gitignore (measured: a gitignored directory is still scanned), so a
 * checked-in fixture would run in every developer's bare `bun test` and cost
 * them minutes. The generated suite therefore lands OUTSIDE the repo by default,
 * and this script warns loudly if pointed inside it. Nothing test-shaped is
 * committed, so ordinary runs stay unaffected by construction rather than by
 * configuration.
 *
 * WHAT IT GENERATES
 * -----------------
 * A suite that is long, noisy, and fails somewhere easy to miss:
 *   - LONG: every test awaits one chain shared through globalThis, so the total
 *     wall-clock is sleeps x tests however the runner schedules them. (bun runs
 *     node:test tests concurrently, which would otherwise collapse the runtime.)
 *   - NOISY: each test logs 8 lines, so a run produces thousands of lines.
 *   - FAILING: one test in the middle asserts a planted marker pair, so the
 *     failure sits far from both ends of the output.
 *
 * USAGE
 * -----
 *   bun scripts/make-dummy-suite.ts                      # ~180s, ~2,500 lines
 *   DUMMY_SLEEP_MS=20 bun scripts/make-dummy-suite.ts    # fast smoke version
 *   bun test /tmp/pi-bgrun-dummy-suite                   # run the suite
 *
 * Tunables (defaults in brackets): DUMMY_OUT_DIR
 * [<system tmpdir>/pi-bgrun-dummy-suite], DUMMY_SLEEP_MS [600], DUMMY_FILES [10],
 * DUMMY_TESTS_PER_FILE [30], DUMMY_FAIL_FILE [5], DUMMY_FAIL_STEP [15].
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(
  process.env.DUMMY_OUT_DIR ?? join(tmpdir(), "pi-bgrun-dummy-suite"),
);
const sleepMs = Number(process.env.DUMMY_SLEEP_MS ?? 600);
const files = Number(process.env.DUMMY_FILES ?? 10);
const perFile = Number(process.env.DUMMY_TESTS_PER_FILE ?? 30);
const failFile = Number(process.env.DUMMY_FAIL_FILE ?? 5);
const failStep = Number(process.env.DUMMY_FAIL_STEP ?? 15);

for (const [name, value] of Object.entries({
  sleepMs,
  files,
  perFile,
  failFile,
  failStep,
})) {
  if (!Number.isFinite(value) || value < 1) {
    console.error(`error: ${name} must be a positive number (got ${value})`);
    process.exit(2);
  }
}

if (outDir === repoRoot || outDir.startsWith(repoRoot + sep)) {
  console.warn(
    `warning: ${outDir} is inside the repo (${repoRoot}).\n` +
      "         `bun test` discovers *.test.ts anywhere in the tree and does not\n" +
      "         respect .gitignore, so a bare `bun test` will now run this suite too.\n" +
      "         Unset DUMMY_OUT_DIR to write outside the repo instead.",
  );
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (let i = 1; i <= files; i++) {
  const n = String(i).padStart(2, "0");
  const failing = i === failFile;
  writeFileSync(
    join(outDir, `part-${n}.test.ts`),
    `// Generated by scripts/make-dummy-suite.ts — do not edit; regenerate instead.
import { test, describe } from "node:test";
import assert from "node:assert/strict";

// Fixture purpose: this suite exists to occupy real wall-clock time and produce
// real output volume. The delay IS the thing under measurement, so a fake timer
// cannot stand in for it — hence a genuine setTimeout. It is generated outside
// the repo so it never runs in CI or in a bare \`bun test\`.
const g = globalThis as unknown as { __chain?: Promise<void> };
function step(): Promise<void> {
  const hold = new Promise<void>((resolve) => setTimeout(resolve, ${sleepMs}));
  g.__chain = (g.__chain ?? Promise.resolve()).then(() => hold);
  return g.__chain;
}

describe("load part ${n}", () => {
  for (let k = 1; k <= ${perFile}; k++) {
    const which = k;
    test(\`step \${String(which).padStart(2, "0")}\`, async () => {
      for (let line = 1; line <= 8; line++) {
        console.log(\`[part ${n} step \${which}] stage \${line}/8 — building, linking, checking\`);
      }
${
  failing
    ? `      if (which === ${failStep}) {
        assert.deepEqual(
          { actual: "DIAGNOSTIC_MARKER_UPSTREAM", got: 1 },
          { expected: "DIAGNOSTIC_MARKER_DOWNSTREAM", got: 2 },
        );
      }
`
    : ""
}      await step();
    });
  }
});
`,
  );
}

const total = files * perFile;
console.log(
  `generated ${files} files in ${outDir}\n` +
    `  tests:    ${total} (${files} files x ${perFile})\n` +
    `  runtime:  ~${((sleepMs * total) / 1000).toFixed(0)}s (${sleepMs}ms x ${total})\n` +
    `  output:   ~${total * 9} lines\n` +
    `  failing:  part ${String(failFile).padStart(2, "0")} step ${failStep}, exit 1\n` +
    `  run it:   bun test ${outDir}`,
);
