#!/usr/bin/env bun
/**
 * Tests for scripts/make-dummy-suite.ts.
 *
 * What needs proving is the fixture's SHAPE CONTRACT — the parts a battery reads
 * and no one can eyeball at a glance: which file the trace's deepest frame names,
 * that a trace line number is where the code actually sits, and that the planted
 * failure really fails. A generator that silently emitted the inline shape, or a
 * stale line number, would send a session looking somewhere else and quietly
 * invalidate a diagnosis cell — which is the whole job of the knob tested here.
 *
 * Generation writes to a temp dir and the knobs below hold the suite at six tiny
 * tests, so the file runs in well under a second and never touches the repo.
 *
 * node:test rather than bun:test, matching extension/index.test.ts: these run
 * under both runners with @types/node alone.
 *
 * BACKWARD-EQUIVALENCE CONTRACT (mirrors the header of make-dummy-suite.ts)
 * ------------------------------------------------------------------------
 * The generator's recorded fixtures are pinned BEHAVIOURALLY, never by bytes.
 *   1. For each recorded fixture and its recorded knobs, the generator MUST keep
 *      reproducing the behaviour that defines the fixture: the file count, the
 *      total test count, the failing test's NAME (never its line), the assertion
 *      kind, and — for a cause-module fixture — a trace whose deepest frame is a
 *      file other than the failing one. The workload shape is pinned the same
 *      way: the sleeps' duration class and the log volume's order of magnitude.
 *      A change to any of these is what must fail this test — it means the
 *      fixture a cell was measured against is no longer the fixture it claims.
 *   2. A pure byte change — a blank line, an import reorder, a comment — alters
 *      no behaviour, so it MUST NOT fail. The afb2bd1 blank-line drift is the
 *      precedent: it moved every recorded hash and invalidated no reported number.
 *   3. Adding a fixture means adding a row to RECORDED_FIXTURES below with its
 *      exact knobs and its behavioural facts.
 *
 * The recorded hashes in the table are DOCUMENTED HISTORY, not a gate. Each is
 * the fixture's files sorted by path, contents concatenated, sha1, first 16 hex
 * — computed at the fixture's RECORDED ABSOLUTE PATH (the generated files embed
 * their own out-dir in the failure's stack trace, so a hash means nothing without
 * that path). The test prints a NOTE when the regenerated bytes differ from a
 * recorded hash, so drift stays visible without being an error: a record's cited
 * hash may legitimately be stale while the behaviour it stood for is unchanged.
 * When a difference IS behavioural, the assertions below are what say so.
 *
 * The fixtures were generated at different generator revisions (red-tail and
 * equiv predate afb2bd1; long-buried and trace-root were generated at it), which
 * is why their recorded hashes are not interchangeable descriptions of "the
 * fixture" — the behavioural facts below are.
 */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { after, test } from "node:test";
import assert from "node:assert/strict";

const script = join(
  dirname(fileURLToPath(import.meta.url)),
  "make-dummy-suite.ts",
);
const root = mkdtempSync(join(tmpdir(), "make-dummy-suite-test-"));
after(() => rmSync(root, { recursive: true, force: true }));

const failingPart = "part-02.test.ts";

interface Generation {
  status: number | null;
  stdout: string;
  stderr: string;
  outDir: string;
}

function generate(name: string, env: Record<string, string> = {}): Generation {
  const outDir = join(root, name);
  const result = spawnSync("bun", ["run", script], {
    encoding: "utf8",
    env: {
      ...process.env,
      DUMMY_OUT_DIR: outDir,
      DUMMY_FILES: "2",
      DUMMY_TESTS_PER_FILE: "3",
      DUMMY_FAIL_FILE: "2",
      DUMMY_FAIL_STEP: "2",
      DUMMY_SLEEP_MS: "1",
      DUMMY_ANNOUNCE_FAILURE: "0",
      ...env,
    },
  });
  return {
    status: result.status,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
    outDir,
  };
}

/** The 1-based line holding `needle`, or 0 — the convention the script itself uses. */
function lineOf(text: string, needle: string): number {
  return text.split("\n").findIndex((line) => line.includes(needle)) + 1;
}

test("cause module: the assertion sits one frame from the failing test, at real lines", () => {
  const { status, stderr, outDir } = generate("cause-on", {
    DUMMY_CAUSE_MODULE: "1",
  });
  assert.equal(status, 0, stderr);

  const harness = readFileSync(join(outDir, "harness.ts"), "utf8");
  const failing = readFileSync(join(outDir, failingPart), "utf8");

  // The module exists and only the failing test reaches for it; Bun discovers
  // tests by name, so harness.ts cannot be picked up as one either.
  assert.match(failing, /import \{ loadStep \} from "\.\/harness";/);
  assert.match(failing, /loadStep\(\);/);

  // The invariant a diagnosis cell reads: the planted block's frames name the
  // lines the code actually sits on, in both files. A drift here is invisible in
  // the fixture's output and would misdirect the session it is built to measure.
  const assertLine = lineOf(harness, "assert.deepEqual");
  const callLine = lineOf(failing, "loadStep();");
  assert.ok(assertLine > 0, "the assertion must exist in the module");
  assert.ok(callLine > 0, "the call site must exist in the failing test");
  assert.ok(
    harness.includes(
      `at loadStep (${join(outDir, "harness.ts")}:${assertLine}:9)`,
    ),
    "the block must name the assertion's real line",
  );
  assert.ok(
    harness.includes(
      `at load part 02 (${join(outDir, failingPart)}:${callLine}:25)`,
    ),
    "the block must name the call site's real line",
  );
  for (const text of [harness, failing]) {
    assert.doesNotMatch(text, /__(FAIL|CALL)_LINE__/);
  }
});

test("cause module: the run fails, and its trace names a file that is not the failing test", () => {
  const { outDir } = generate("cause-on-run", { DUMMY_CAUSE_MODULE: "1" });
  const run = spawnSync("bun", ["test", outDir], { encoding: "utf8" });
  assert.notEqual(run.status, 0, "the planted failure must fail the run");

  const trace = `${run.stdout ?? ""}\n${run.stderr ?? ""}`;
  // These two lines ARE the cell: the deepest frame is the cause's own file, and
  // the frame under it is the call site — not runner plumbing, not the same file.
  assert.match(trace, /at loadStep \(.*harness\.ts:\d+:\d+\)/);
  assert.match(
    trace,
    new RegExp(`at load part 02 \\(.*${failingPart}:\\d+:\\d+\\)`),
  );
});

test("cause module: off by default, the assertion stays inline", () => {
  const { status, stderr, outDir } = generate("cause-off");
  assert.equal(status, 0, stderr);
  assert.equal(
    existsSync(join(outDir, "harness.ts")),
    false,
    "the module is opt-in — existing fixtures and their recorded shapes depend on it",
  );
  const failing = readFileSync(join(outDir, failingPart), "utf8");
  assert.match(failing, /assert\.deepEqual\(/);
  assert.doesNotMatch(failing, /loadStep/);
});

test("cause module: a value other than 0 or 1 is rejected, not ignored", () => {
  const { status, stderr } = generate("cause-bad", { DUMMY_CAUSE_MODULE: "2" });
  assert.equal(status, 2);
  assert.match(stderr, /DUMMY_CAUSE_MODULE must be 0 or 1/);
});

// ── Backward-equivalence contract: the recorded fixtures ────────────────────
// Each row records a fixture a cell was measured against. `knobs` regenerates
// it; the behavioural fields below are what the contract pins (see the contract
// at the top of this file and the generator's header). `recordedSha` is
// DOCUMENTED HISTORY ONLY — a mismatch prints a note, never a failure.
interface FixtureRecord {
  name: string;
  knobs: Record<string, string>;
  /** Count of generated part-NN.test.ts files. */
  files: number;
  /** Total tests the run reports: files x tests per file. */
  tests: number;
  /** The failing test's name — never its line number. */
  failingTest: string;
  /** The assertion the planted failure makes. */
  assertKind: string;
  /** True when the trace's deepest frame names a file other than the failing one. */
  causeModule: boolean;
  /** The workload shape: what makes one cell's numbers comparable to another's. */
  sleepMs: number;
  linesPerTest: number;
  durationClass: DurationClass;
  volumeClass: VolumeClass;
  /** The absolute path the fixture was generated at; the hash depends on it. */
  recordedPath: string;
  /** Documented history, not a gate. */
  recordedSha: string;
  /** Where a record quotes a different hash than the table's, and why. */
  recordNote?: string;
}

type DurationClass = "sub-second" | "seconds" | "minutes";
type VolumeClass = "tens" | "hundreds" | "thousands";

/** The order-of-magnitude class of the wall-clock the recorded sleeps imply. */
function durationClass(seconds: number): DurationClass {
  if (seconds < 1) return "sub-second";
  if (seconds < 60) return "seconds";
  return "minutes";
}

/** The order-of-magnitude class of the log volume the recorded knobs imply. */
function volumeClass(lines: number): VolumeClass {
  if (lines < 100) return "tens";
  if (lines < 1000) return "hundreds";
  return "thousands";
}

const RECORDED_FIXTURES: FixtureRecord[] = [
  {
    // Cell 1 (docs/benchmark/runs/red-tail-short/RUNSHEET.md) quotes its hash.
    // It is the fixture the afb2bd1 drift broke: before the fix the same knobs
    // produced dedf28f736923ad8 (one blank line too many after the imports).
    name: "red-tail",
    knobs: {
      DUMMY_FILES: "2",
      DUMMY_TESTS_PER_FILE: "4",
      DUMMY_SLEEP_MS: "1",
      DUMMY_FAIL_FILE: "2",
      DUMMY_FAIL_STEP: "4",
      DUMMY_LINES_PER_TEST: "2",
      DUMMY_ANNOUNCE_FAILURE: "0",
      DUMMY_CAUSE_MODULE: "0",
    },
    files: 2,
    tests: 8,
    failingTest: "load part 02 > step 04",
    assertKind: "assert.deepEqual",
    causeModule: false,
    sleepMs: 1,
    linesPerTest: 2,
    durationClass: "sub-second",
    volumeClass: "tens",
    recordedPath: "/private/tmp/red-tail-fixture",
    recordedSha: "0bfe00ed1d9866b9",
  },
  {
    // Cell 3 (docs/benchmark/runs/trace-root/RUNSHEET.md) quotes its hash. The
    // cause-module shape: the deepest trace frame names harness.ts, a file the
    // session has no other reason to open.
    name: "trace-root",
    knobs: {
      DUMMY_FILES: "2",
      DUMMY_TESTS_PER_FILE: "4",
      DUMMY_SLEEP_MS: "1",
      DUMMY_FAIL_FILE: "2",
      DUMMY_FAIL_STEP: "4",
      DUMMY_LINES_PER_TEST: "2",
      DUMMY_ANNOUNCE_FAILURE: "0",
      DUMMY_CAUSE_MODULE: "1",
    },
    files: 2,
    tests: 8,
    failingTest: "load part 02 > step 04",
    assertKind: "assert.deepEqual",
    causeModule: true,
    sleepMs: 1,
    linesPerTest: 2,
    durationClass: "sub-second",
    volumeClass: "tens",
    recordedPath: "/private/tmp/trace-root-fixture",
    recordedSha: "605aba38baf5c6ad",
  },
  {
    // Cell 2 (docs/benchmark/runs/long-buried/RUNSHEET.md). This fixture predates
    // the fix at the DRIFTED revision, so its RUNSHEET quotes 6671002e6f186546
    // where the fixed generator yields a80876eac7089297 — one blank line, and a
    // one-line frame shift with it (part-05.test.ts:59 vs :58). No reported
    // number depends on either, which is why the behaviour is what the row pins.
    name: "long-buried",
    knobs: {
      DUMMY_FILES: "10",
      DUMMY_TESTS_PER_FILE: "30",
      DUMMY_SLEEP_MS: "600",
      DUMMY_FAIL_FILE: "5",
      DUMMY_FAIL_STEP: "15",
      DUMMY_LINES_PER_TEST: "2",
      DUMMY_ANNOUNCE_FAILURE: "0",
      DUMMY_CAUSE_MODULE: "0",
      DUMMY_FAIL_FAST: "0",
    },
    files: 10,
    tests: 300,
    failingTest: "load part 05 > step 15",
    assertKind: "assert.deepEqual",
    causeModule: false,
    sleepMs: 600,
    linesPerTest: 2,
    durationClass: "minutes",
    volumeClass: "hundreds",
    recordedPath: "/private/tmp/long-buried-fixture",
    recordedSha: "a80876eac7089297",
    recordNote:
      "RUNSHEET quotes 6671002e6f186546 from the drifted revision; the fixed generator yields a80876eac7089297. One blank line moved and the quoted frame is :59 where a fresh fixture is :58 — the same failing test, count and trace shape, so no reported metric changes",
  },
  {
    // The pilot's fixture (docs/benchmark/runs/pilot/MANIFEST.md), the attended
    // method check. It predates afb2bd1 too, so recordNote explains why its
    // quoted hash is stale while its behaviour is exactly the table's.
    name: "pilot",
    knobs: {
      DUMMY_FILES: "2",
      DUMMY_TESTS_PER_FILE: "6",
      DUMMY_SLEEP_MS: "50",
      DUMMY_FAIL_FILE: "2",
      DUMMY_FAIL_STEP: "4",
      DUMMY_LINES_PER_TEST: "2",
      DUMMY_ANNOUNCE_FAILURE: "0",
      DUMMY_CAUSE_MODULE: "0",
    },
    files: 2,
    tests: 12,
    failingTest: "load part 02 > step 04",
    assertKind: "assert.deepEqual",
    causeModule: false,
    sleepMs: 50,
    linesPerTest: 2,
    durationClass: "sub-second",
    volumeClass: "tens",
    recordedPath: "/private/tmp/equiv-fixture",
    recordedSha: "8bf97128414cba0b",
    recordNote:
      "MANIFEST quotes 8bf97128414cba0b, taken before the inline shape was restored; the fixed generator yields a750aa16ff9ce4ab. Same 2 files, 12 tests and failing test — only the bytes moved",
  },
];

/** The first integer captured by `pattern`, failing the test if it is absent. */
function matchInt(text: string, pattern: RegExp): number {
  const match = text.match(pattern);
  assert.ok(match, `expected to find ${pattern} in the generated fixture`);
  return Number(match[1]);
}

/**
 * The behavioural facts of a generated fixture, read back from its source: what
 * the contract pins, as opposed to the bytes it happens to be written in. The
 * failing test's name, the total test count and the file count come from the
 * fixture's own output text (its failure block and summary), not from arithmetic
 * over the knobs, so a generator that stopped emitting them would fail here.
 */
interface FixtureFacts {
  files: number;
  tests: number;
  failingTest: string;
  assertKind: string;
  sleepMs: number;
  linesPerTest: number;
  failingFile: string;
  deepestFrameFile: string;
}

function fixtureFacts(outDir: string): FixtureFacts {
  const names = readdirSync(outDir).sort();
  const partFiles = names.filter((name) => /^part-\d+\.test\.ts$/.test(name));
  assert.ok(partFiles.length > 0, "the generator emitted no part files");
  const texts = names.map((name) => readFileSync(join(outDir, name), "utf8"));
  const all = texts.join("\n");

  // The total is files x the loop bound each part file declares; the fixture's
  // own summary must agree with that arithmetic, so neither can drift silently.
  const perFile = matchInt(
    readFileSync(join(outDir, partFiles[0]), "utf8"),
    /for \(let k = 1; k <= (\d+); k\+\+\)/,
  );
  const files = partFiles.length;
  const tests = files * perFile;
  const summary = all.match(/load run summary: (\d+) files, (\d+) tests/);
  assert.ok(summary, "the generated suite must declare its own size");
  assert.equal(Number(summary[1]), files, "summary file count vs generated files");
  assert.equal(Number(summary[2]), tests, "summary test count vs files x per-file");

  // The failing test's NAME — the identity a record quotes — from its failure block.
  const failure = all.match(/load part (\d+) > step (\d+)/);
  assert.ok(failure, "the planted failure must name its test");
  const failingFile = `part-${failure[1]}.test.ts`;

  // The assertion kind: a real assertion failure, not a terse stub.
  assert.match(
    all,
    /AssertionError \[ERR_ASSERTION\]: Expected values to be strictly deep-equal/,
  );
  assert.match(all, /assert\.deepEqual\(/);
  const assertKind = "assert.deepEqual";

  // The trace shape. A cause-module fixture's deepest frame is the module (a file
  // other than the failing test); the inline shape's is the failing test itself.
  const harness = names.find((name) => name === "harness.ts");
  if (harness) {
    assert.match(
      readFileSync(join(outDir, harness), "utf8"),
      /at loadStep \(/,
      "the cause module must contribute the deepest frame",
    );
  } else {
    assert.match(
      readFileSync(join(outDir, failingFile), "utf8"),
      /at TestContext\.<anonymous> \(/,
      "the inline shape's deepest frame must name the failing test",
    );
  }

  return {
    files,
    tests,
    failingTest: `load part ${failure[1]} > step ${failure[2]}`,
    assertKind,
    sleepMs: matchInt(all, /setTimeout\(resolve, (\d+)\)/),
    linesPerTest: matchInt(all, /for \(let line = 1; line <= (\d+); line\+\+\)/),
    failingFile,
    deepestFrameFile: harness ?? failingFile,
  };
}

/**
 * The documented hash, computed the way the records state it: files sorted by
 * path, contents concatenated, sha1, first 16 hex. The scratch out-dir path is
 * normalised back to the recorded path first, because the generated files embed
 * their own out-dir path in the failure's stack trace. Reported as history only.
 */
function hashFixture(outDir: string, recordedPath: string): string {
  const files = readdirSync(outDir)
    .map((name) => join(outDir, name))
    .sort();
  const hash = createHash("sha1");
  for (const file of files) {
    hash.update(readFileSync(file, "utf8").split(outDir).join(recordedPath));
  }
  return hash.digest("hex").slice(0, 16);
}

test("recorded fixtures: each regenerates with the behaviour the contract pins", () => {
  for (const fixture of RECORDED_FIXTURES) {
    const where = fixture.name;
    const outDir = join(root, `recorded-${fixture.name}`);
    const result = spawnSync("bun", ["run", script], {
      encoding: "utf8",
      env: { ...process.env, DUMMY_OUT_DIR: outDir, ...fixture.knobs },
    });
    assert.equal(result.status, 0, `${where}: ${result.stderr}`);

    const facts = fixtureFacts(outDir);

    // The behaviour that makes it THIS fixture — a different failing test, a
    // different count or an altered trace shape is a different fixture.
    assert.equal(facts.files, fixture.files, `${where}: file count moved`);
    assert.equal(facts.tests, fixture.tests, `${where}: total test count moved`);
    assert.equal(
      facts.failingTest,
      fixture.failingTest,
      `${where}: the failing test's name moved`,
    );
    assert.equal(
      facts.assertKind,
      fixture.assertKind,
      `${where}: the assertion kind moved`,
    );
    assert.equal(facts.sleepMs, fixture.sleepMs, `${where}: the sleep knob moved`);
    assert.equal(
      facts.linesPerTest,
      fixture.linesPerTest,
      `${where}: the log density moved`,
    );

    // The workload shape a cell's numbers are comparable within.
    assert.equal(
      durationClass((facts.sleepMs * facts.tests) / 1000),
      fixture.durationClass,
      `${where}: the duration class the sleeps imply moved`,
    );
    assert.equal(
      volumeClass(facts.tests * facts.linesPerTest),
      fixture.volumeClass,
      `${where}: the log-volume order of magnitude moved`,
    );

    // The trace shape a diagnosis cell reads: for a cause-module fixture the
    // deepest frame must be a file OTHER than the failing test.
    if (fixture.causeModule) {
      assert.equal(
        facts.deepestFrameFile,
        "harness.ts",
        `${where}: the deepest frame must be the cause module`,
      );
      assert.notEqual(
        facts.deepestFrameFile,
        facts.failingFile,
        `${where}: the deepest frame must not be the failing test`,
      );
    } else {
      assert.equal(
        facts.deepestFrameFile,
        facts.failingFile,
        `${where}: the inline shape's deepest frame is the failing test`,
      );
    }

    // Bytes are documented history, not a gate: a difference is a NOTE. The
    // behaviour assertions above are what fail when the fixture actually changed.
    const regenerated = hashFixture(outDir, fixture.recordedPath);
    if (regenerated !== fixture.recordedSha) {
      console.log(
        `note: ${where} regenerated to ${regenerated}, not the recorded ` +
          `${fixture.recordedSha}. The bytes differ; the behaviour above is ` +
          `unchanged.` +
          (fixture.recordNote ? ` (${fixture.recordNote})` : ""),
      );
    }

    // A cheap fixture is also RUN, so the facts above are confirmed against the
    // real run, not only the generated source. long-buried is left to the source
    // assertions: its recorded sleeps make it a three-minute run, which no unit
    // test should pay for.
    if ((facts.sleepMs * facts.tests) / 1000 < 5) {
      const run = spawnSync("bun", ["test", outDir], { encoding: "utf8" });
      const output = `${run.stdout ?? ""}\n${run.stderr ?? ""}`;
      assert.notEqual(
        run.status,
        0,
        `${where}: the planted failure must fail the run`,
      );
      assert.match(
        output,
        new RegExp(`\\(fail\\) ${fixture.failingTest}`),
        `${where}: the run must report the expected failing test`,
      );
      assert.match(
        output,
        new RegExp(
          `Ran ${fixture.tests} tests across ${fixture.files} files`,
        ),
        `${where}: the run must report the expected size`,
      );
      assert.match(
        output,
        /operator: "deepStrictEqual"/,
        `${where}: the run must fail a deep-equality assertion`,
      );
      if (fixture.causeModule) {
        assert.match(
          output,
          /at loadStep \(.*harness\.ts:\d+:\d+\)/,
          `${where}: the run's deepest frame must name the cause module`,
        );
      } else {
        assert.match(
          output,
          new RegExp(`at .*${facts.failingFile}:\\d+:\\d+`),
          `${where}: the run's deepest frame must name the failing test`,
        );
      }
    }
  }
});
